### ISSUE TITLE
对于 lila 充满好奇

### ISSUE THREAD

**Issue by dkvirus** [senntyou/lila#17]
我是从 sf 上看你的系列文章 "前端架构之路" 看到 lila 找过来的，我不确定 lila 是为了解决什么问题而出现的，400 多次 commit 可以看出来 lila 是想要做些什么的。能否写一篇介绍 lila 的文章，揭开 lila 的神秘面纱。

**Comment by senntyou** [comment]
主要用于需要多入口构建的项目，为了简化构建流程而设计的。基于 Gulp 的任务流，但内部对 Gulp 做了封装。

我的其他的一些项目中有用到：
- [react-app-starter](https://github.com/senntyou/react-app-starter)
- [react-ts-app-starter](https://github.com/senntyou/react-ts-app-starter)
- [vue-app-starter](https://github.com/senntyou/vue-app-starter)
